### ISSUE TITLE
Vertical loss of mouse interaction after css transform

### ISSUE THREAD

**Issue by jsprog** [c-smile/sciter-js-sdk#16]
When using css transform, vertical interaction is getting lost for regions not overlapping with the space occupied without the transformation applied.

- This is affecting elements with `position: inline-block;`
- Relative elements aren't affected.
- Absolute elements are having a different kind of bug by shrinking the bounding box horizontally (regardless of transform)

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CSS Transform</title>

    <style>
        #target {
            display: inline-block;
            padding: 10px;
            border: solid 1px black;
            background-color: rgba(0, 255, 0, 0.4);
            cursor: pointer;
        }
        #target:hover {
            background-color: rgba(255, 69, 0, 0.8);;
        }
        #target {
            /* un-comment to test with translate */
            /* transform: translate(25px, 25px); */

            /* un-comment to test with scale */
            /* transform: scale(3.0); */

            /* un-comment to test with rotation */
            /* transform: rotate(70deg); */
        }
        #target {
            /* un-comment to fix vertical mouse interation */
            /* position: relative; */

            /* un-commnet to see a different bug that shrinks the bounding box horizontally */
            /* position: absolute; */
        }
    </style>
</head>
<body style="padding: 100px 150px;">
    <div id="target">TARGET</div>

    <script>
        const target = document.querySelector('#target')
        target.addEventListener('click', () => {
            console.log('target clicked.')
        })
    </script>

</body>
</html>
```

**Comment by c-smile** [comment]
Should be fixed in 4.4.5.6

**Comment by jsprog** [comment]
After some tests under Windows x64 and Linux x64, I can confirm that this issue is staying with **4.4.5.6, revision 8335, 2020-11-17**.

Likely you missed to merge the fix [1- [css] hit test fix on inline-block/transform elements;](https://github.com/c-smile/sciter-js-sdk/blob/main/logfile.md)

**Comment by jsprog** [comment]
Already fixed with the last update.
Thanks.
