### ISSUE TITLE
4.4.7.0 causes segmentation fault on macOS

### ISSUE THREAD

**Issue by AlecHaring** [c-smile/sciter-js-sdk#77]
There seems to be something wrong with the macOS build in the 0549c17c3041928daae8e133208a69e5b599a40e commit. Opening something like usciterjs that implements the SDK will immediately crash with a segmentation fault. I tested it on Windows and it seems to work fine so it seems to be exclusive to the macOS build. I tested the main Sciter SDK as well which yielded the same result -- works fine.  Here are the details from the crash log:
```
Process:               usciterjs [48436]
Path:                  /private/var/folders/*/usciterjs.app/Contents/MacOS/usciterjs
Identifier:            terrainformatica.usciterjs
Version:               1.0 (1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           usciterjs [48436]
User ID:               501

Date/Time:             2021-04-18 14:57:11.808 -0400
OS Version:            macOS 11.2.3 (20D91)
Report Version:        12
Bridge OS Version:     5.2 (18P4347)
Anonymous UUID:        671E2E21-A8E6-B3E8-3D79-A6B4C6FC5508

Sleep/Wake UUID:       850BFD0B-24B0-4052-B0D6-90BA375BA104

Time Awake Since Boot: 180000 seconds
Time Since Wake:       4300 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [48436]

VM Regions Near 0:
--> 
    __TEXT                      108f80000-1090c4000    [ 1296K] r-x/r-x SM=COW  /var/folders/*/usciterjs.app/Contents/MacOS/usciterjs

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   ???                           	000000000000000000 0 + 0
1   terrainformatica.usciterjs    	0x0000000108f85736 uimain(std::__1::function<int ()>) + 166
2   terrainformatica.usciterjs    	0x0000000108f83f43 main + 953
3   libdyld.dylib                 	0x00007fff20458621 start + 1

Thread 1:
0   libsystem_pthread.dylib       	0x00007fff20439458 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	0x00007fff20439458 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	0x00007fff20439458 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	0x00007fff20439458 start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	0x00007fff20439458 start_wqthread + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x000000010b7cc240  rbx: 0x000000000000000c  rcx: 0x00000001090c2c96  rdx: 0x0000000000000031
  rdi: 0x00006000030ad388  rsi: 0x0000239cb53fd380  rbp: 0x00007ffee6c7f910  rsp: 0x00007ffee6c7f8c8
   r8: 0x0000000000000001   r9: 0xffffffff00000000  r10: 0x00007fff88a46928  r11: 0x00007fff20401661
  r12: 0x0aaaaaaaaaaaaaaa  r13: 0x00007fea8270ffa0  r14: 0x00007ffee6c7f9c0  r15: 0x00006000030ad388
  rip: 0x0000000000000000  rfl: 0x0000000000010202  cr2: 0x0000000000000000
  
Logical CPU:     2
Error Code:      0x00000014 (no mapping for user instruction read)
Trap Number:     14

Thread 0 instruction stream not available.

Thread 0 last branch register state not available.
```

**Comment by c-smile** [comment]
Yeah, something went wrong. 

I've reuploaded it. Should work now.

**Comment by AlecHaring** [comment]
It seems like the issue still exists. I found that the issue with usciterjs was that the libsciter.dylib file in its Frameworks folder is outdated and replacing that with the one in bin/macosx folder fixes that problem. Things like glfw-opengl and PySciter still crash though.

**Comment by 105th** [comment]
Сonfirm same problem at 4.4.7.3: `segmentation fault`
